apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config-map
  namespace: fiap-tc-f2
data:
  AUTH_SERVICE_URL: "http://auth-service-svc:8001"
  PORT: "8005"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/913901705985/evaluation-events"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
  AWS_REGION: "us-east-1"