apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: fiap-tc-f2
 
spec:
  selector:
    matchLabels:
      app: analytics-service
  replicas: 1
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: 913901705985.dkr.ecr.us-east-1.amazonaws.com/fiap-tc-f2-reg:analitycs-service-v1
          ports:
            - containerPort: 8005
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
        
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3 
          
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secret
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secret
                  key: AWS_SECRET_ACCESS_KEY

            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secret
                  key: AWS_SESSION_TOKEN 
            
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: analytics-service-config-map
                  key: PORT
            - name: AWS_SQS_URL
              valueFrom:
                configMapKeyRef:
                  name: analytics-service-config-map
                  key: AWS_SQS_URL
            - name: AWS_DYNAMODB_TABLE
              valueFrom:
                configMapKeyRef:
                  name: analytics-service-config-map
                  key: AWS_DYNAMODB_TABLE
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: analytics-service-config-map
                  key: AUTH_SERVICE_URL
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: analytics-service-config-map
                  key: AWS_REGION
                  
