apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: fiap-tc-f2
 
type: Opaque
data:
  SERVICE_API_KEY: dG1fa2V5XzllZjBhNTE1MDZmNzYxNzhjOWNlMjNjZWRjZWMzZjBmZGNmZTAxZmYzNGI1NThjNjI2MmVkMmY4ZDNkZmFmNzQ=
  AWS_ACCESS_KEY_ID: QVNJQVRKTEJBQTQyV1hRVFRSQkY=
  AWS_SECRET_ACCESS_KEY: RkxCVis0dERaS0M3NDFSdENPT2xMcm9DYTdZOVZLOTd3RVFVcG1BSA==
  AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVIc2FDWFZ6TFhkbGMzUXRNaUpITUVVQ0lRRHd6OXNiYnJpTTNvYlF4eWUvVTRXNEtkZ3p3QVBrM0pBY3QraFJMN0xyQVFJZ1craVIybUdPV0VxY1krSnI1SENaMGE3U0lZWTM2bGVnREIyOEhRQzZyWDBxcWdJSVJCQUFHZ3d5TWpZeU1qWXdOemsxTkRFaURPb1ZIYnRWVjI4RTNhdTZHQ3FIQW9ucmNQcXhyZmdKbkNPQVhBNEduSDVqdWdWVGtPM1pPRUJCSHp0ZzV6a0dXUGdhQ1BpUkxtTUtTYnNHZmt3ZjB1TENCbW93bWFxdG5jSjhoVU9lT2lSV0oyU3ArUFB2MUt0aGhySmNQV0l3c1B1OEkxbytyT3ZiQTNXcE5QU1ZDeTB1elJkWHBmR0U2Y2dSeUozbXIzY3krNVUyUzRlQmxTd2F1RFIrZ2N3Y2FZdzREMk9iL05nQ0U5TklOK25aTE9RZ1k0VEUxNW9Xd1BVSnJQdHBXUGliclZLbnFIWTRWNVZNbVgxQzVtNGhtMGxnL2JoamlNWU01ZkUxaUlWV256ekx1Y3UvTDNuT1lWWDJKeWcrakUrL3BSZzZiNDNiZnVEUFRyR2JPQVpEeEVwWjdvMXNXQVNMSGlvQVZLR1VpRVE2NVpQazdTM1RKOUplSTQrNDBnaFJKalprK3B3Z01NMk0rTTBHT3AwQnZqODZGS1U5NG1qN3FIL2NhY1Y3THBNc01heWhWRk16cmIvbFk1Zjd6U0N6TGNkN2tWWnBVbTJUZzkyUGdBS1ByNWNEVEU2T1oyaENDZTlaOE00RFBqQ0QxV2gvblpkQmF5bGVjOEptNElFSndVZlRiMkZML1NHZlVnb2VMdWVsSEJpVVpUMTVIeVk4bmdRdzdlL3hxYXFvZFl4dUZtTjZOWGRGMmx1eXJUNVZzYWk4UXdQbEs4WUZtOFFyazdoRWpUZlpsenZDbHpOcE1LUWpDdz09