apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: targeting-service-httproute
 
spec:
  parentRefs:
    - name: targeting-service-gateway
      sectionName: http-targeting-service-8003
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: targeting-service-svc
          port: 8003