apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: targeting-service-gateway
 
spec:
  gatewayClassName: nginx
  listeners:
  - name: http-targeting-service-8003
    protocol: HTTP
    port: 8003
    allowedRoutes:
      namespaces:
        from: Same 