apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: fiap-tc-f2
 
type: Opaque
data:
  SERVICE_API_KEY: dG1fa2V5XzczYjMzZjMxYzc4ZmY4MzhkMzY1MTYwMDgyMzU1MDJjNGQ0MTU5ZjdjNDA5ZTczODY4OWMxMWMwZWU2NTU4YWQ=
  AWS_ACCESS_KEY_ID: QVNJQTVKU0dKTE1BNDIyVkpCWVQ=
  AWS_SECRET_ACCESS_KEY: QkxFTW95aUZSM0FTVU02ZzFiU2FyeWRoWGhYRHNoSDBmTXpHTlBNQw==
  AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVLNy8vLy8vLy8vLy93RWFDWFZ6TFhkbGMzUXRNaUpJTUVZQ0lRRFczUytkY0FHTithdXZqb0hXbEZuZGFQeVdyYzFWYVN6bk9xQ3R3RitNL0FJaEFMVnIvbWE4UnBlOTZidkR1MlM3ZXVsUmp5ZHBISlpxL0h6aitZRzN5SFEzS3JJQ0NIY1FBQm9NT1RFek9UQXhOekExT1RnMUlndzBvQTFHNkViRVFtajFwR0VxandLVlNzODNPRTZBUDVKaXc1b2Y3bUw2cEc2UHVyQjF5cmJvcjRwQVNIdzZSWCs4d0IwTC9FcE1TWFBMZFRCclhQc3U3QlZvSGI1ZVhXcFppbmVpeGdVcHN2WldsN2dJdlJpY3NzSG1oMkU0TVRWVTF6M1RicmsrTXJXaXZKNVlzZW02Z2tFVG82d3NaMmdXVGlsVzBMeFo0TWVpZWlXSTgvV0FTSHF6TmdTcUFmUU1ZSkphNEVRV3ZlbE9lTFBZMG1FZGlIdTlNb3NtbE1PN0k3ZlJmWkMraFM2b2hsK2kzeG16dFNjeWRFUXRKOSt0aCtwdGdZeTljcUdaVkZrYjNuU1IvZnRBNDAxVXMzc1BicXE5RWRPN3MvMzRmZW1YUkIzL1o0aHl3a1RKbTNWVDR0S0FmNFp0dk5JWkk3MmFSZDRtNDZXSHUyemxCdVJMSEhpWENtSmw1L2haUFNBOVpOeStwZ25PVXpyZU1LV2dnODRHT3B3QjZHbTFxTlozckt0dzgzb2c1T3pQeUlGcE5vZ0dqU0RaS0VuMmt1M0Q4UzlIMVVsNUtLOU1wT2lEUWYwMHptY1psK0hRREZDZGU2akpxOHpIbEFHMWpFcXRZYmNySUJQdHdnU2UwdVpFMDkvNHQ1N1p6M1hkRmp4ak8xNXk2dTkwY3dWc2JCTnpXWFhCQ1NzUWdXU2owUzIxNDJlV2U0aXZNcDZ5dVp6aC9JbXZqWUt0dmJGUzRNRm1aaC9uUTN6VmJLa2V5QWdKWmNoeDBQRkY=